services:
  devcontainer:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Overrides default command so things don't shut down after the process ends.
    # command: /bin/sh -c "while sleep 1000; do :; done"
